name: TimedWings
version: '${project.version}'
main: tc.arcadia.timedwings.TimedWings
api-version: '1.13'
authors:
  - ArcadiaPlugins
  - FurkanZhlp
softdepend:
  - PlaceholderAPI
  - FabledSkyBlock
  - WorldGuard
commands:
  timedwings:
    description: Management command of TimedWings plugin.
    aliases:
      - tw
      - tempfly
      - tfly